# Generated by Django 5.0.7 on 2024-07-21 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('poperty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poperty',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='poperty/'),
        ),
        migrations.AddField(
            model_name='poperty',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
        migrations.AddField(
            model_name='poperty',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='superficy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='type',
            field=models.CharField(blank=True, choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('store', 'Store')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='poperty',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
